default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - release
  - deploy

variables:
  # DOCKER_HOST: tcp://docker:2376
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DATA_TRAINING_FOLDER: data
  MODELS_TRAINING_FOLDER: models
  OUT_TRAINING_FOLDER:  out
  TELEMETRY_NODE_HOST: 127.0.0.1
  TELEMETRY_NODE_PORT: 5000

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run --entrypoint "/bin/bash" $CONTAINER_TEST_IMAGE ./gitlab-ci-test.sh 

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master 

# deploy:
#  stage: deploy
#  script:
#    - ./deploy.sh
#  only:
#    - main
#  environment: production
