name: Publish Docker image on FLUIDOS Docker Hub

on:
  push:
    branches: [ "github" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "github" ]
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set GIT_TAG env var
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fluidos
          password: ${{ secrets.DOCKER_HUB_WRITE_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: fluidos/energy-predictor

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: fluidos
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_WRITE_TOKEN }}
          DOCKERHUB_REPOSITORY: fluidos/energy-predictor

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: GIT_TAG=${{ env.GIT_TAG }}