name: Publish Docker image on FLUIDOS Docker Hub

on:
  push:
    branches: [ "github" ]
    tags: [ 'v*.*.*' ]
  # pull_request:
  #   branches: [ "github" ]
  release:
    types: [published]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: fluidos/energy-predictor
  IMAGE_BASE_NAME: energy-predictor
  ORG_NAME: fluidos
  BASE_BRANCH: github


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true 

      - name: Set running Git tag
        run: echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set last version Git tag
        run: echo "VERSION=$(git describe --tags --always --abbrev=0)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fluidos
          password: ${{ secrets.DOCKER_HUB_WRITE_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: fluidos/energy-predictor

      - name: Push README to Docker Hub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: fluidos
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_TOKEN }}
        with:
          destination_container_repo: fluidos/energy-predictor
          provider: dockerhub
          short_description: 'Predicting the energy and carbon demand of FLUIDOS nodes.'
          readme_file: 'README.md'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BASE_BRANCH }} , ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }} , ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # - name: Build Docker image with local git tag 
      #   run: |
      #     docker build --build-arg GIT_TAG=${{ env.GIT_TAG }} -t fluidos/energy-predictor:${{ env.GIT_TAG }} .
      #     
      # - name: Push Docker image
      #   run: |
      #     docker push fluidos/energy-predictor:${{ env.GIT_TAG }}